workflows:
  android-offline-scanner-workflow:
    name: Build Bills Generator APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Generate Flutter project scaffolding
        script: |
          flutter create . --platforms=android
      - name: Force Min SDK Version 24 for Android
        script: |
          if [ -f "android/app/build.gradle.kts" ]; then
            echo 'android { defaultConfig { minSdk = 24 } }' >> android/app/build.gradle.kts
          elif [ -f "android/app/build.gradle" ]; then
            echo 'android { defaultConfig { minSdkVersion 24 } }' >> android/app/build.gradle
          fi
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-shrink --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
